
image: hysds/pge-base:v4.1.0-beta.3

build_image:
  stage: build

  before_script:
  - docker info
  - docker inspect -f '{{.State.Running}}' registry

  script:
    - docker images

  tags:
    - hysds

  only:
   - main
