build_image:
  stage: build

  before_script:
    - docker info
    - docker inspect -f '{{.State.Running}}' registry
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY

  script:
    - VERDI_IMAGE=mas.maap-project.org/root/register-job-hysds-v4/maap-hysds-verdi:v4.1.0-beta.3
    - DOCKER_GID=$(getent group docker | cut -d ':' -f3)
    - docker run --pull=always -u ${UID}:${DOCKER_GID} -v /var/run/docker.sock:/var/run/docker.sock:ro -v ${PWD}:${PWD} -w ${PWD} ${VERDI_IMAGE} ${PWD}/build.sh

  tags:
    - shell

  only:
   - main
