build_image:
  stage: build

  script:
    - docker images
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - VERDI_IMAGE=hysds/verdi:v4.1.0-beta.3
    - docker run -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:${PWD} -w ${PWD} ${VERDI_IMAGE} bash build.sh

  tags:
    - shell

  only:
   - main
