build_image:
  stage: build

  before_script:
    - docker info
    - docker inspect -f '{{.State.Running}}' registry

  script:
    - VERDI_IMAGE=hysds/verdi:v4.1.0-beta.3
    - DOCKER_GID=$(getent group docker | cut -d ':' -f3)
    - docker run -u ${UID}:${DOCKER_GID} -v /var/run/docker.sock:/var/run/docker.sock:ro -v ${PWD}:${PWD} -w ${PWD} ${VERDI_IMAGE} ${PWD}/build.sh

  tags:
    - shell

  only:
   - main
