build_image:
  stage: build

  before_script:
    - docker info
    - docker inspect -f '{{.State.Running}}' registry

  script:
    - VERDI_IMAGE=hysds/verdi:v4.1.0-beta.3
    - docker run -u ${UID} -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:${PWD} -w ${PWD} --entrypoint /bin/bash ${VERDI_IMAGE} bash build.sh

  tags:
    - shell

  only:
   - main
